_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.11.0
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
activation:
    value: sigmoid
batch_size:
    value: 64
epochs:
    value: 5
hidden_layers:
    value: 5
layer_size:
    value: 32
learning_rate:
    value: 0.0001
optimizer:
    value: nadam
weight_decay:
    value: 0
weight_init:
    value: random
