_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.11.0
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
activation:
    value: relu
batch_size:
    value: 32
epochs:
    value: 10
hidden_size:
    value: 128
learning_rate:
    value: 0.001
loss:
    value: cross_entropy
num_layers:
    value: 2
optimizer:
    value: sgd
weight_init:
    value: random
