wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
hidden_size:
  value: 128
learning_rate:
  value: 0.001
num_layers:
  value: 2
optimizer:
  value: sgd
weight_init:
  value: xavier
