_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 13
                - 14
                - 16
                - 23
                - 55
            "4": 3.11.0
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
activation:
    value: relu
batch_size:
    value: 32
beta:
    value: 0.9
beta1:
    value: 0.9
beta2:
    value: 0.999
dataset:
    value: fashion_mnist
earlystop:
    value: true
epochs:
    value: 10
epsilon:
    value: 1e-10
hidden_size:
    value: 128
learning_rate:
    value: 0.001
logger:
    value: true
loss:
    value: cross_entropy
mode:
    value: test
momentum:
    value: 0.9
num_layers:
    value: 2
optimizer:
    value: sgd
probab:
    value: true
wandb_entity:
    value: mm21b044
wandb_project:
    value: DL-Assign-1
weight_decay:
    value: 0.0001
weight_init:
    value: he
